Repository helm/community, pull requests merged in 2020-10, with the labels that each got.

#148 Removing initial election details from governance
  governance/governance.md
Labels: size/S

#151 Updating link for Zoom call
  communication.md
Labels: size/XS

#136 HIP for OCI support
  hips/hip-0006.md
Labels: size/L
