Repository helm/community, pull requests merged in 2021-04, with the labels that each got.

#178 fix(*): use correct branch for helm repo
  README.md
  Teams.md
  communication.md
  helm-maintainers-onboarding-guide.md
Labels: size/S

#181 fix(*): fix misspellings
  helm-maintainers-onboarding-guide.md
Labels: size/XS

#138 HIP-0011: Informational Helm CRD HIP
  hips/hip-0011.md
Labels: size/L
