Repository helm/community, pull requests merged in 2021-06, with the labels that each got.

#187 Updating maintainer info
  governance/README.md
  governance/governance.md
  helm-maintainers-onboarding-guide.md
Labels: size/M

#179 HIP for Helm 4 planning and development process
  hips/hip-0012.md
Labels: size/L

#198 Add Martin as org maintainer
  MAINTAINERS.md
Labels: size/XS
