Repository helm/community, pull requests merged in 2025-02, with the labels that each got.

#381 H4HIP: Adding a HIP on charts v3
  hips/README.md
  hips/hip-0020.md
Labels: size/L

#372 H4HIP: Enhanced logging library for Helm
  hips/README.md
  hips/hip-0021.md
Labels: size/M

#374 H4HIP: Wait with kstatus
  hips/hip-0999.md
Labels: size/L

#389 Updating kstatus HIP to have a number
  hips/README.md
  hips/hip-0022.md
Labels: size/XS

#392 adding in the static example for impementing slog
  hips/hip-0021.md
Labels: size/S
